/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const KnockoutEntryType = IDL.Variant({
  'PreQuarterfinals' : IDL.Null,
  'Semifinals' : IDL.Null,
  'Quarterfinals' : IDL.Null,
});
export const AdvancementType = IDL.Variant({
  'KnockoutEntry' : KnockoutEntryType,
  'NextStage' : IDL.Nat,
});
export const RoundRobinStageConfig = IDL.Record({
  'id' : IDL.Nat,
  'advancementRuleWinner' : AdvancementType,
  'advancementRuleRunnerUp' : AdvancementType,
});
export const StageType = IDL.Variant({
  'Knockout' : IDL.Null,
  'RoundRobin' : RoundRobinStageConfig,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const StageView = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'stageType' : StageType,
});
export const DrawsView = IDL.Record({
  'stages' : IDL.Vec(IDL.Tuple(IDL.Nat, StageView)),
  'groups' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text)),
});
export const TournamentView = IDL.Record({
  'name' : IDL.Text,
  'creationDate' : Time,
  'draws' : DrawsView,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'username' : IDL.Text,
  'joinDate' : Time,
  'isPrivate' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGroupToAllTournaments' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'addGroupToTournament' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'addStageToAllTournaments' : IDL.Func([IDL.Nat, IDL.Text, StageType], [], []),
  'addStageToTournament' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, StageType],
      [IDL.Bool],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createTournament' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'deleteTournament' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllTournaments' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, TournamentView))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTournament' : IDL.Func([IDL.Nat], [IDL.Opt(TournamentView)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeNewProfile' : IDL.Func([IDL.Bool], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setProfilePrivacy' : IDL.Func([IDL.Bool], [IDL.Bool], []),
  'updateTournamentName' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'updateUsername' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const KnockoutEntryType = IDL.Variant({
    'PreQuarterfinals' : IDL.Null,
    'Semifinals' : IDL.Null,
    'Quarterfinals' : IDL.Null,
  });
  const AdvancementType = IDL.Variant({
    'KnockoutEntry' : KnockoutEntryType,
    'NextStage' : IDL.Nat,
  });
  const RoundRobinStageConfig = IDL.Record({
    'id' : IDL.Nat,
    'advancementRuleWinner' : AdvancementType,
    'advancementRuleRunnerUp' : AdvancementType,
  });
  const StageType = IDL.Variant({
    'Knockout' : IDL.Null,
    'RoundRobin' : RoundRobinStageConfig,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const StageView = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'stageType' : StageType,
  });
  const DrawsView = IDL.Record({
    'stages' : IDL.Vec(IDL.Tuple(IDL.Nat, StageView)),
    'groups' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text)),
  });
  const TournamentView = IDL.Record({
    'name' : IDL.Text,
    'creationDate' : Time,
    'draws' : DrawsView,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'username' : IDL.Text,
    'joinDate' : Time,
    'isPrivate' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGroupToAllTournaments' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'addGroupToTournament' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'addStageToAllTournaments' : IDL.Func(
        [IDL.Nat, IDL.Text, StageType],
        [],
        [],
      ),
    'addStageToTournament' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, StageType],
        [IDL.Bool],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTournament' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'deleteTournament' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllTournaments' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, TournamentView))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTournament' : IDL.Func([IDL.Nat], [IDL.Opt(TournamentView)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeNewProfile' : IDL.Func([IDL.Bool], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setProfilePrivacy' : IDL.Func([IDL.Bool], [IDL.Bool], []),
    'updateTournamentName' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'updateUsername' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };