/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const KnockoutEntryType = IDL.Variant({
  'PreQuarterfinals' : IDL.Null,
  'Semifinals' : IDL.Null,
  'Quarterfinals' : IDL.Null,
});
export const AdvancementType = IDL.Variant({
  'KnockoutEntry' : KnockoutEntryType,
  'NextStage' : IDL.Nat,
});
export const RoundRobinStageConfig = IDL.Record({
  'id' : IDL.Nat,
  'advancementRuleWinner' : AdvancementType,
  'advancementRuleRunnerUp' : AdvancementType,
});
export const StageType = IDL.Variant({
  'Knockout' : IDL.Null,
  'RoundRobin' : RoundRobinStageConfig,
});
export const Stage = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'stageType' : StageType,
});

export const idlService = IDL.Service({
  'addGroup' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'addStage' : IDL.Func([IDL.Nat, IDL.Text, StageType], [], []),
  'getAllStages' : IDL.Func([], [IDL.Vec(IDL.Tuple(IDL.Nat, Stage))], []),
  'getStage' : IDL.Func([IDL.Nat], [IDL.Opt(Stage)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const KnockoutEntryType = IDL.Variant({
    'PreQuarterfinals' : IDL.Null,
    'Semifinals' : IDL.Null,
    'Quarterfinals' : IDL.Null,
  });
  const AdvancementType = IDL.Variant({
    'KnockoutEntry' : KnockoutEntryType,
    'NextStage' : IDL.Nat,
  });
  const RoundRobinStageConfig = IDL.Record({
    'id' : IDL.Nat,
    'advancementRuleWinner' : AdvancementType,
    'advancementRuleRunnerUp' : AdvancementType,
  });
  const StageType = IDL.Variant({
    'Knockout' : IDL.Null,
    'RoundRobin' : RoundRobinStageConfig,
  });
  const Stage = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'stageType' : StageType,
  });
  
  return IDL.Service({
    'addGroup' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'addStage' : IDL.Func([IDL.Nat, IDL.Text, StageType], [], []),
    'getAllStages' : IDL.Func([], [IDL.Vec(IDL.Tuple(IDL.Nat, Stage))], []),
    'getStage' : IDL.Func([IDL.Nat], [IDL.Opt(Stage)], []),
  });
};

export const init = ({ IDL }) => { return []; };