/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AdvancementType = { 'KnockoutEntry' : KnockoutEntryType } |
  { 'NextStage' : bigint };
export interface DrawsView {
  'stages' : Array<[bigint, StageView]>,
  'groups' : Array<[bigint, string]>,
}
export type KnockoutEntryType = { 'PreQuarterfinals' : null } |
  { 'Semifinals' : null } |
  { 'Quarterfinals' : null };
export interface RoundRobinStageConfig {
  'id' : bigint,
  'advancementRuleWinner' : AdvancementType,
  'advancementRuleRunnerUp' : AdvancementType,
}
export type StageType = { 'Knockout' : null } |
  { 'RoundRobin' : RoundRobinStageConfig };
export interface StageView {
  'id' : bigint,
  'name' : string,
  'stageType' : StageType,
}
export type Time = bigint;
export interface TournamentView {
  'owner' : [] | [Principal],
  'name' : string,
  'creationDate' : Time,
  'draws' : DrawsView,
}
export interface UserProfile {
  'id' : Principal,
  'username' : string,
  'joinDate' : Time,
  'isPrivate' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGroupToAllTournaments' : ActorMethod<[bigint, string], undefined>,
  'addGroupToTournament' : ActorMethod<[bigint, bigint, string], boolean>,
  'addStageToAllTournaments' : ActorMethod<
    [bigint, string, StageType],
    undefined
  >,
  'addStageToTournament' : ActorMethod<
    [bigint, bigint, string, StageType],
    boolean
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createTournament' : ActorMethod<[bigint, string], undefined>,
  'deleteTournament' : ActorMethod<[bigint], boolean>,
  'getAllTournaments' : ActorMethod<[], Array<[bigint, TournamentView]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getTournament' : ActorMethod<[bigint], [] | [TournamentView]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeNewProfile' : ActorMethod<[boolean], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setProfilePrivacy' : ActorMethod<[boolean], boolean>,
  'updateTournamentName' : ActorMethod<[bigint, string], boolean>,
  'updateUsername' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];