/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface TournamentView {
    name: string;
    creationDate: Time;
    draws: DrawsView;
}
export interface DrawsView {
    stages: Array<[bigint, StageView]>;
    groups: Array<[bigint, string]>;
}
export interface RoundRobinStageConfig {
    id: bigint;
    advancementRuleWinner: AdvancementType;
    advancementRuleRunnerUp: AdvancementType;
}
export type StageType = {
    __kind__: "Knockout";
    Knockout: null;
} | {
    __kind__: "RoundRobin";
    RoundRobin: RoundRobinStageConfig;
};
export interface StageView {
    id: bigint;
    name: string;
    stageType: StageType;
}
export type AdvancementType = {
    __kind__: "KnockoutEntry";
    KnockoutEntry: KnockoutEntryType;
} | {
    __kind__: "NextStage";
    NextStage: bigint;
};
export interface UserProfile {
    id: Principal;
    username: string;
    joinDate: Time;
    isPrivate: boolean;
}
export enum KnockoutEntryType {
    PreQuarterfinals = "PreQuarterfinals",
    Semifinals = "Semifinals",
    Quarterfinals = "Quarterfinals"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addGroupToAllTournaments(groupId: bigint, groupName: string): Promise<void>;
    addGroupToTournament(tournamentId: bigint, groupId: bigint, groupName: string): Promise<boolean>;
    addStageToAllTournaments(stageId: bigint, name: string, stageType: StageType): Promise<void>;
    addStageToTournament(tournamentId: bigint, stageId: bigint, name: string, stageType: StageType): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createTournament(id: bigint, name: string): Promise<void>;
    deleteTournament(id: bigint): Promise<boolean>;
    getAllTournaments(): Promise<Array<[bigint, TournamentView]>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getTournament(id: bigint): Promise<TournamentView | null>;
    getUserProfile(userId: Principal): Promise<UserProfile | null>;
    initializeNewProfile(isPrivate: boolean): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setProfilePrivacy(isPrivate: boolean): Promise<boolean>;
    updateTournamentName(id: bigint, newName: string): Promise<boolean>;
    updateUsername(newUsername: string): Promise<void>;
}
import type { AdvancementType as _AdvancementType, DrawsView as _DrawsView, KnockoutEntryType as _KnockoutEntryType, RoundRobinStageConfig as _RoundRobinStageConfig, StageType as _StageType, StageView as _StageView, Time as _Time, TournamentView as _TournamentView, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addGroupToAllTournaments(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGroupToAllTournaments(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGroupToAllTournaments(arg0, arg1);
            return result;
        }
    }
    async addGroupToTournament(arg0: bigint, arg1: bigint, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addGroupToTournament(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGroupToTournament(arg0, arg1, arg2);
            return result;
        }
    }
    async addStageToAllTournaments(arg0: bigint, arg1: string, arg2: StageType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addStageToAllTournaments(arg0, arg1, to_candid_StageType_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStageToAllTournaments(arg0, arg1, to_candid_StageType_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async addStageToTournament(arg0: bigint, arg1: bigint, arg2: string, arg3: StageType): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addStageToTournament(arg0, arg1, arg2, to_candid_StageType_n1(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStageToTournament(arg0, arg1, arg2, to_candid_StageType_n1(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createTournament(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTournament(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTournament(arg0, arg1);
            return result;
        }
    }
    async deleteTournament(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTournament(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTournament(arg0);
            return result;
        }
    }
    async getAllTournaments(): Promise<Array<[bigint, TournamentView]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTournaments();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTournaments();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTournament(arg0: bigint): Promise<TournamentView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTournament(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTournament(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeNewProfile(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeNewProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeNewProfile(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setProfilePrivacy(arg0: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setProfilePrivacy(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setProfilePrivacy(arg0);
            return result;
        }
    }
    async updateTournamentName(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTournamentName(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTournamentName(arg0, arg1);
            return result;
        }
    }
    async updateUsername(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUsername(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUsername(arg0);
            return result;
        }
    }
}
function from_candid_AdvancementType_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdvancementType): AdvancementType {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_DrawsView_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DrawsView): DrawsView {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_KnockoutEntryType_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KnockoutEntryType): KnockoutEntryType {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_RoundRobinStageConfig_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoundRobinStageConfig): RoundRobinStageConfig {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_StageType_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StageType): StageType {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_StageView_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StageView): StageView {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_TournamentView_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TournamentView): TournamentView {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TournamentView]): TournamentView | null {
    return value.length === 0 ? null : from_candid_TournamentView_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    creationDate: _Time;
    draws: _DrawsView;
}): {
    name: string;
    creationDate: Time;
    draws: DrawsView;
} {
    return {
        name: value.name,
        creationDate: value.creationDate,
        draws: from_candid_DrawsView_n15(_uploadFile, _downloadFile, value.draws)
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stages: Array<[bigint, _StageView]>;
    groups: Array<[bigint, string]>;
}): {
    stages: Array<[bigint, StageView]>;
    groups: Array<[bigint, string]>;
} {
    return {
        stages: from_candid_vec_n17(_uploadFile, _downloadFile, value.stages),
        groups: value.groups
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    stageType: _StageType;
}): {
    id: bigint;
    name: string;
    stageType: StageType;
} {
    return {
        id: value.id,
        name: value.name,
        stageType: from_candid_StageType_n21(_uploadFile, _downloadFile, value.stageType)
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    advancementRuleWinner: _AdvancementType;
    advancementRuleRunnerUp: _AdvancementType;
}): {
    id: bigint;
    advancementRuleWinner: AdvancementType;
    advancementRuleRunnerUp: AdvancementType;
} {
    return {
        id: value.id,
        advancementRuleWinner: from_candid_AdvancementType_n25(_uploadFile, _downloadFile, value.advancementRuleWinner),
        advancementRuleRunnerUp: from_candid_AdvancementType_n25(_uploadFile, _downloadFile, value.advancementRuleRunnerUp)
    };
}
function from_candid_tuple_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, _TournamentView]): [bigint, TournamentView] {
    return [
        value[0],
        from_candid_TournamentView_n13(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, _StageView]): [bigint, StageView] {
    return [
        value[0],
        from_candid_StageView_n19(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Knockout: null;
} | {
    RoundRobin: _RoundRobinStageConfig;
}): {
    __kind__: "Knockout";
    Knockout: null;
} | {
    __kind__: "RoundRobin";
    RoundRobin: RoundRobinStageConfig;
} {
    return "Knockout" in value ? {
        __kind__: "Knockout",
        Knockout: value.Knockout
    } : "RoundRobin" in value ? {
        __kind__: "RoundRobin",
        RoundRobin: from_candid_RoundRobinStageConfig_n23(_uploadFile, _downloadFile, value.RoundRobin)
    } : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    KnockoutEntry: _KnockoutEntryType;
} | {
    NextStage: bigint;
}): {
    __kind__: "KnockoutEntry";
    KnockoutEntry: KnockoutEntryType;
} | {
    __kind__: "NextStage";
    NextStage: bigint;
} {
    return "KnockoutEntry" in value ? {
        __kind__: "KnockoutEntry",
        KnockoutEntry: from_candid_KnockoutEntryType_n27(_uploadFile, _downloadFile, value.KnockoutEntry)
    } : "NextStage" in value ? {
        __kind__: "NextStage",
        NextStage: value.NextStage
    } : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    PreQuarterfinals: null;
} | {
    Semifinals: null;
} | {
    Quarterfinals: null;
}): KnockoutEntryType {
    return "PreQuarterfinals" in value ? KnockoutEntryType.PreQuarterfinals : "Semifinals" in value ? KnockoutEntryType.Semifinals : "Quarterfinals" in value ? KnockoutEntryType.Quarterfinals : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, _TournamentView]>): Array<[bigint, TournamentView]> {
    return value.map((x)=>from_candid_tuple_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, _StageView]>): Array<[bigint, StageView]> {
    return value.map((x)=>from_candid_tuple_n18(_uploadFile, _downloadFile, x));
}
function to_candid_AdvancementType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdvancementType): _AdvancementType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_KnockoutEntryType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: KnockoutEntryType): _KnockoutEntryType {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_RoundRobinStageConfig_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoundRobinStageConfig): _RoundRobinStageConfig {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_StageType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StageType): _StageType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    advancementRuleWinner: AdvancementType;
    advancementRuleRunnerUp: AdvancementType;
}): {
    id: bigint;
    advancementRuleWinner: _AdvancementType;
    advancementRuleRunnerUp: _AdvancementType;
} {
    return {
        id: value.id,
        advancementRuleWinner: to_candid_AdvancementType_n5(_uploadFile, _downloadFile, value.advancementRuleWinner),
        advancementRuleRunnerUp: to_candid_AdvancementType_n5(_uploadFile, _downloadFile, value.advancementRuleRunnerUp)
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "Knockout";
    Knockout: null;
} | {
    __kind__: "RoundRobin";
    RoundRobin: RoundRobinStageConfig;
}): {
    Knockout: null;
} | {
    RoundRobin: _RoundRobinStageConfig;
} {
    return value.__kind__ === "Knockout" ? {
        Knockout: value.Knockout
    } : value.__kind__ === "RoundRobin" ? {
        RoundRobin: to_candid_RoundRobinStageConfig_n3(_uploadFile, _downloadFile, value.RoundRobin)
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "KnockoutEntry";
    KnockoutEntry: KnockoutEntryType;
} | {
    __kind__: "NextStage";
    NextStage: bigint;
}): {
    KnockoutEntry: _KnockoutEntryType;
} | {
    NextStage: bigint;
} {
    return value.__kind__ === "KnockoutEntry" ? {
        KnockoutEntry: to_candid_KnockoutEntryType_n7(_uploadFile, _downloadFile, value.KnockoutEntry)
    } : value.__kind__ === "NextStage" ? {
        NextStage: value.NextStage
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: KnockoutEntryType): {
    PreQuarterfinals: null;
} | {
    Semifinals: null;
} | {
    Quarterfinals: null;
} {
    return value == KnockoutEntryType.PreQuarterfinals ? {
        PreQuarterfinals: null
    } : value == KnockoutEntryType.Semifinals ? {
        Semifinals: null
    } : value == KnockoutEntryType.Quarterfinals ? {
        Quarterfinals: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
