/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Stage {
    id: bigint;
    name: string;
    stageType: StageType;
}
export interface RoundRobinStageConfig {
    id: bigint;
    advancementRuleWinner: AdvancementType;
    advancementRuleRunnerUp: AdvancementType;
}
export type StageType = {
    __kind__: "Knockout";
    Knockout: null;
} | {
    __kind__: "RoundRobin";
    RoundRobin: RoundRobinStageConfig;
};
export type AdvancementType = {
    __kind__: "KnockoutEntry";
    KnockoutEntry: KnockoutEntryType;
} | {
    __kind__: "NextStage";
    NextStage: bigint;
};
export enum KnockoutEntryType {
    PreQuarterfinals = "PreQuarterfinals",
    Semifinals = "Semifinals",
    Quarterfinals = "Quarterfinals"
}
export interface backendInterface {
    addGroup(id: bigint, name: string): Promise<void>;
    addStage(id: bigint, name: string, stageType: StageType): Promise<void>;
    getAllStages(): Promise<Array<[bigint, Stage]>>;
    getStage(id: bigint): Promise<Stage | null>;
}
import type { AdvancementType as _AdvancementType, KnockoutEntryType as _KnockoutEntryType, RoundRobinStageConfig as _RoundRobinStageConfig, Stage as _Stage, StageType as _StageType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addGroup(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGroup(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGroup(arg0, arg1);
            return result;
        }
    }
    async addStage(arg0: bigint, arg1: string, arg2: StageType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addStage(arg0, arg1, to_candid_StageType_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStage(arg0, arg1, to_candid_StageType_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async getAllStages(): Promise<Array<[bigint, Stage]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStages();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStages();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStage(arg0: bigint): Promise<Stage | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStage(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStage(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AdvancementType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdvancementType): AdvancementType {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_KnockoutEntryType_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KnockoutEntryType): KnockoutEntryType {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_RoundRobinStageConfig_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoundRobinStageConfig): RoundRobinStageConfig {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_StageType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StageType): StageType {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Stage_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Stage): Stage {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Stage]): Stage | null {
    return value.length === 0 ? null : from_candid_Stage_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    stageType: _StageType;
}): {
    id: bigint;
    name: string;
    stageType: StageType;
} {
    return {
        id: value.id,
        name: value.name,
        stageType: from_candid_StageType_n13(_uploadFile, _downloadFile, value.stageType)
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    advancementRuleWinner: _AdvancementType;
    advancementRuleRunnerUp: _AdvancementType;
}): {
    id: bigint;
    advancementRuleWinner: AdvancementType;
    advancementRuleRunnerUp: AdvancementType;
} {
    return {
        id: value.id,
        advancementRuleWinner: from_candid_AdvancementType_n17(_uploadFile, _downloadFile, value.advancementRuleWinner),
        advancementRuleRunnerUp: from_candid_AdvancementType_n17(_uploadFile, _downloadFile, value.advancementRuleRunnerUp)
    };
}
function from_candid_tuple_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, _Stage]): [bigint, Stage] {
    return [
        value[0],
        from_candid_Stage_n11(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Knockout: null;
} | {
    RoundRobin: _RoundRobinStageConfig;
}): {
    __kind__: "Knockout";
    Knockout: null;
} | {
    __kind__: "RoundRobin";
    RoundRobin: RoundRobinStageConfig;
} {
    return "Knockout" in value ? {
        __kind__: "Knockout",
        Knockout: value.Knockout
    } : "RoundRobin" in value ? {
        __kind__: "RoundRobin",
        RoundRobin: from_candid_RoundRobinStageConfig_n15(_uploadFile, _downloadFile, value.RoundRobin)
    } : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    KnockoutEntry: _KnockoutEntryType;
} | {
    NextStage: bigint;
}): {
    __kind__: "KnockoutEntry";
    KnockoutEntry: KnockoutEntryType;
} | {
    __kind__: "NextStage";
    NextStage: bigint;
} {
    return "KnockoutEntry" in value ? {
        __kind__: "KnockoutEntry",
        KnockoutEntry: from_candid_KnockoutEntryType_n19(_uploadFile, _downloadFile, value.KnockoutEntry)
    } : "NextStage" in value ? {
        __kind__: "NextStage",
        NextStage: value.NextStage
    } : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    PreQuarterfinals: null;
} | {
    Semifinals: null;
} | {
    Quarterfinals: null;
}): KnockoutEntryType {
    return "PreQuarterfinals" in value ? KnockoutEntryType.PreQuarterfinals : "Semifinals" in value ? KnockoutEntryType.Semifinals : "Quarterfinals" in value ? KnockoutEntryType.Quarterfinals : value;
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, _Stage]>): Array<[bigint, Stage]> {
    return value.map((x)=>from_candid_tuple_n10(_uploadFile, _downloadFile, x));
}
function to_candid_AdvancementType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdvancementType): _AdvancementType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_KnockoutEntryType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: KnockoutEntryType): _KnockoutEntryType {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_RoundRobinStageConfig_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoundRobinStageConfig): _RoundRobinStageConfig {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_StageType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StageType): _StageType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    advancementRuleWinner: AdvancementType;
    advancementRuleRunnerUp: AdvancementType;
}): {
    id: bigint;
    advancementRuleWinner: _AdvancementType;
    advancementRuleRunnerUp: _AdvancementType;
} {
    return {
        id: value.id,
        advancementRuleWinner: to_candid_AdvancementType_n5(_uploadFile, _downloadFile, value.advancementRuleWinner),
        advancementRuleRunnerUp: to_candid_AdvancementType_n5(_uploadFile, _downloadFile, value.advancementRuleRunnerUp)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "Knockout";
    Knockout: null;
} | {
    __kind__: "RoundRobin";
    RoundRobin: RoundRobinStageConfig;
}): {
    Knockout: null;
} | {
    RoundRobin: _RoundRobinStageConfig;
} {
    return value.__kind__ === "Knockout" ? {
        Knockout: value.Knockout
    } : value.__kind__ === "RoundRobin" ? {
        RoundRobin: to_candid_RoundRobinStageConfig_n3(_uploadFile, _downloadFile, value.RoundRobin)
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "KnockoutEntry";
    KnockoutEntry: KnockoutEntryType;
} | {
    __kind__: "NextStage";
    NextStage: bigint;
}): {
    KnockoutEntry: _KnockoutEntryType;
} | {
    NextStage: bigint;
} {
    return value.__kind__ === "KnockoutEntry" ? {
        KnockoutEntry: to_candid_KnockoutEntryType_n7(_uploadFile, _downloadFile, value.KnockoutEntry)
    } : value.__kind__ === "NextStage" ? {
        NextStage: value.NextStage
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: KnockoutEntryType): {
    PreQuarterfinals: null;
} | {
    Semifinals: null;
} | {
    Quarterfinals: null;
} {
    return value == KnockoutEntryType.PreQuarterfinals ? {
        PreQuarterfinals: null
    } : value == KnockoutEntryType.Semifinals ? {
        Semifinals: null
    } : value == KnockoutEntryType.Quarterfinals ? {
        Quarterfinals: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
